Software/
    GUI/
        IAQ_GUI.py
    HAT/
        IAQ_DAC43608.py
        IAQ_Mux.py
    Sensors/
        IAQ_Sensor.py
        IAQ_MQGas.py
        IAQ_BME680.py
        IAQ_SDS011.py
        IAQ_SCD30.py
        IAQ_GPS.py
    third_party/
        Adafruit_I2C.py
        Adafruit_ADS1x15.py
    IAQ_AnalogPortController.py
    IAQ_Exceptions.py
    IAQ_FileHandler.py
    IAQ_Logger.py
    IAQ_Config.py
