Software/
    Config/
    GUI/
        IAQ_GUI.py
    HAT/
        IAQ_DAC43608.py
        IAQ_Mux.py
    Sensors/
        IAQ_Sensor.py
        IAQ_MqGas.py
    third_party/
        bme680-python
    IAQ_AnalogPortController.py
    IAQ_Exceptions.py
    IAQ_FileHandler.py
    IAQ_Logger.py
